basic.forever(function () {
    music.playMelody("E C E C E C E C ", 274)
    music.playMelody("C5 A C5 A C5 A C5 A ", 274)
    music.playMelody("- C C5 A F C G F ", 274)
    music.playMelody("D C E D F E D C ", 274)
    music.playMelody("- G - G E G E G ", 274)
    music.playMelody("F C5 A F D C E F ", 274)
    music.playMelody("C5 B A C - E D C ", 274)
    music.playMelody("A G F G D C - - ", 274)
    music.playMelody("E - E C5 A C - C ", 304)
    music.playMelody("C5 - C5 A F - G C ", 269)
    music.playMelody("C5 B A B D B A - ", 274)
    music.playMelody("A C A C D A C A ", 433)
    music.playMelody("C F C C5 A E C - ", 317)
    music.playMelody("C - E C5 A C - F ", 433)
    music.playMelody("G - C C5 E C - C ", 200)
    music.playMelody("F E G C C5 A D F ", 246)
    music.playMelody("F C D A - D - D ", 390)
    music.playMelody("C - C C5 A E C - ", 274)
    music.playMelody("E F G E C5 A F E ", 807)
    music.playMelody("- C5 B A F E D C ", 606)
    music.playMelody("D C5 F C5 D G - C5 ", 1396)
    music.playMelody("G C5 B G E G - G ", 10145)
    music.playMelody("C E C E F G F G ", 1436749)
    music.playMelody("F E F G F E F G ", 12546786)
})
